version: '3'

services:
  eld:
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_DYNAMODB_TABLE_PROPERTY: ${DEPOT_ENVIRONMENT}ConfigurationDynamoTableProperties
      AWS_REGION: ap-southeast-2
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      JAVA_OPTS: -Djava.awt.headless=true -Dspring.profiles.active=local -Xms484M -Xmx968M -XX:MetaspaceSize=256M -XX:MaxMetaspaceSize=768M -XX:CompressedClassSpaceSize=171M -XX:+UnlockDiagnosticVMOptions -Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=n

    image: 212136148154.dkr.ecr.ap-southeast-2.amazonaws.com/eld
    # links:
    #   - elddb:eld-rds.test.erdmg.com
    networks:
      app_net:
        ipv4_address: 172.19.1.20
# uncomment to deploy locally built eld war
    volumes:
    - ${HOME}/eroad/application/components/eld/eld-war/target/eld-war-0-SNAPSHOT.war:/usr/local/tomcat/webapps/eld.war
    - ./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml


  # elddb:
  #   image: postgres
  #   networks:
  #     app_net:
  #       ipv4_address: 172.19.1.97

  memcached:
    image: 212136148154.dkr.ecr.ap-southeast-2.amazonaws.com/mirrored/docker.io/library/memcached
    networks:
      app_net:
        ipv4_address: 172.19.1.4

  portal:
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_DYNAMODB_TABLE_PROPERTY: ${DEPOT_ENVIRONMENT}ConfigurationDynamoTableProperties
      AWS_REGION: ap-southeast-2
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      JAVA_OPTS: -DMEMCACHED_NODE_01=memcached:11211 -DMEMCACHED_NODE_02=memcached:11211 -Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=n
    image: 212136148154.dkr.ecr.ap-southeast-2.amazonaws.com/portal
    networks:
      app_net:
        ipv4_address: 172.19.1.7
    volumes:
    - ./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
# uncomment to deploy locally built portal war
      # - ${HOME}/eroad/application/portal/portal/target/Portal-0-SNAPSHOT.war:/usr/local/tomcat/webapps/Portal.war

  rabbitmq:
    image: 212136148154.dkr.ecr.ap-southeast-2.amazonaws.com/ci/rabbitmq
    networks:
      app_net:
        aliases:
        - rabbitmq.test.erdmg.com
        - rabbitmq.dev.erdmg.com
        ipv4_address: 172.19.1.64

  nginx:
    image: 212136148154.dkr.ecr.ap-southeast-2.amazonaws.com/mirrored/docker.io/library/nginx
    networks:
      app_net:
        aliases:
        - eld-svc.test.erdmg.com
        - eld-svc.dev.erdmg.com
        ipv4_address: 172.19.1.2
    volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf

networks:
  app_net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.19.1.0/24
      driver: default
