version: '3'

services:
  dvir:
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_DYNAMODB_TABLE_PROPERTY: devConfigurationDynamoTableProperties
      AWS_REGION: ap-southeast-2
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
    image: 212136148154.dkr.ecr.ap-southeast-2.amazonaws.com/dvir
    links:
      - dvirdb:dvir-rds.dev.erdmg.com
    networks:
      app_net:
        ipv4_address: 172.19.1.98
# uncomment to deploy locally built dvir war
#    volumes:
#      - ${HOME}/eroad/application/components/inspection/dvir-war/target/dvir-war-0-SNAPSHOT.war


  dvirdb:
    image: postgres
    networks:
      app_net:
        ipv4_address: 172.19.1.97

  memcached:
    image: memcached
    networks:
      app_net:
        ipv4_address: 172.19.1.99

  portal:
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_DYNAMODB_TABLE_PROPERTY: devConfigurationDynamoTableProperties
      AWS_REGION: ap-southeast-2
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      JAVA_OPTS: -DMEMCACHED_NODE_01=memcached:11211 -DMEMCACHED_NODE_02=memcached:11211
    image: 212136148154.dkr.ecr.ap-southeast-2.amazonaws.com/portal
    links:
      - memcached:memcached
      - dvir:dvir.v1.rest
    networks:
      app_net:
        ipv4_address: 172.19.1.2
# uncomment to deploy locally built portal war
#    volumes:
#      - ${HOME}/eroad/application/portal/portal/target/Portal-0-SNAPSHOT.war:/usr/local/tomcat/webapps/Portal.war

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.1.0/24
      driver: default

