version: '3'

services:
  app:
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_DYNAMODB_TABLE_PROPERTY: devConfigurationDynamoTableProperties
      AWS_REGION: ap-southeast-2
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      # Uncomment to enable JVM debugging on port 9009
      #DEBUG_GLASSFISH: debug
    image: 212136148154.dkr.ecr.ap-southeast-2.amazonaws.com/development/glassfish3-app-node:latest
    networks:
      app_net:
        ipv4_address: 172.19.1.25

  mail:
    image: mailhog/mailhog:latest
    networks:
      app_net:
        ipv4_address: 172.19.1.41

  memcached:
    image: memcached
    networks:
      app_net:
        ipv4_address: 172.19.1.99

  portal:
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_DYNAMODB_TABLE_PROPERTY: devConfigurationDynamoTableProperties
      AWS_REGION: ap-southeast-2
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      JAVA_OPTS: -DMEMCACHED_NODE_01=memcached:11211 -DMEMCACHED_NODE_02=memcached:11211
    image: 212136148154.dkr.ecr.ap-southeast-2.amazonaws.com/portal
    networks:
      app_net:
        ipv4_address: 172.19.1.95

  nginx:
    image: nginx
    networks:
      app_net:
        aliases:
          - central-svc.dev.erdmg.com
        ipv4_address: 172.19.1.2
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.1.0/24
      driver: default

