version: '3'

services:
  app:
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_DYNAMODB_TABLE_PROPERTY: ${DEPOT_ENVIRONMENT}ConfigurationDynamoTableProperties
      AWS_REGION: ${AWS_REGION}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=9009
      # Uncomment to enable JVM debugging on port 9009
      DEBUG_GLASSFISH: debug
      AUTODEPLOY: "false"
    image: 212136148154.dkr.ecr.ap-southeast-2.amazonaws.com/development/glassfish5-app-node:latest
    ports:
    - 9009:9009
    - 80:80
    - 8080:8080
    - 4848:4848 # Admin http port; username admin:eroad
    networks:
      app_net:
        ipv4_address: 172.19.1.25
    volumes:
    - ./start.sh:/opt/eroad/glassfish/start.sh
    - /home/sam.wang@Eroad.local/dev/engineering/billing-service/billing-ear/target/billing-ear-1-SNAPSHOT.ear:/opt/glassfish5/glassfish/domains/domain1/autodeploy/billing-ear.ear

  mail:
    image: 212136148154.dkr.ecr.ap-southeast-2.amazonaws.com/mirrored/docker.io/mailhog/mailhog:latest
    networks:
      app_net:
        ipv4_address: 172.19.1.41

  memcached:
    image: 212136148154.dkr.ecr.ap-southeast-2.amazonaws.com/mirrored/docker.io/library/memcached
    networks:
      app_net:
        ipv4_address: 172.19.1.99

  portal:
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_DYNAMODB_TABLE_PROPERTY: ${DEPOT_ENVIRONMENT}ConfigurationDynamoTableProperties
      AWS_REGION: ${AWS_REGION}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      JAVA_OPTS: -DMEMCACHED_NODE_01=memcached:11211 -DMEMCACHED_NODE_02=memcached:11211 -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=7000
    image: 212136148154.dkr.ecr.ap-southeast-2.amazonaws.com/portal
    ports:
      - 8088:8080
      - 7000:7000    
    networks:
      app_net:
        ipv4_address: 172.19.1.95
    volumes:
      #- /home/sam.wang@Eroad.local/eroad/application/portal/portal/target/Portal-0-SNAPSHOT.war:/usr/local/tomcat/webapps/Portal.war
      - ${LOCAL_CODE_BASE}/portal/target/Portal-0-SNAPSHOT:/usr/local/tomcat/webapps/Portal
      # - ${LOCAL_CODE_BASE}/portal/target/classes:/usr/local/tomcat/webapps/Portal/WEB-INF/classes
      - ${LOCAL_CODE_BASE}/portal/src/main/webapp/WEB-INF/jsp:/usr/local/tomcat/webapps/Portal/WEB-INF/jsp
      - ${LOCAL_CODE_BASE}/portal/src/main/webapp/javascript:/usr/local/tomcat/webapps/Portal/javascript
      - ${LOCAL_CODE_BASE}/portal/src/main/webapp/css:/usr/local/tomcat/webapps/Portal/css
  nginx:
    image: 212136148154.dkr.ecr.ap-southeast-2.amazonaws.com/mirrored/docker.io/library/nginx
    networks:
      app_net:
        aliases:
        - central-svc.dev.erdmg.com
        # - vehiclecharging-svc.napp.erdmg.com
        # - vehiclecharging-svc.test.erdmg.com
        - billing-svc.apacpp.erdmg.com
        - billing-svc.test.erdmg.com
        ipv4_address: 172.19.1.2
    volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf

networks:
  app_net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.19.1.0/24
      driver: default

