version: '3'

services:
  portal:
    image: 212136148154.dkr.ecr.ap-southeast-2.amazonaws.com/portal
    environment:
      AWS_REGION: ap-southeast-2
      AWS_DYNAMODB_TABLE_PROPERTY: ${DEPOT_ENVIRONMENT}ConfigurationDynamoTableProperties
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      JAVA_OPTS: -DMEMCACHED_NODE_01=memcached:11211 -DMEMCACHED_NODE_02=memcached:11211 -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000
     # Uncomment to enable JMX connectivity
     # CATALINA_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9000 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false
    networks:
      app_net:
        ipv4_address: 172.19.1.17
    links:
    - memcached:memcached
    volumes:
#      uncomment to deploy locally built portal war
#      - ./dynamicconfig.properties:/usr/local/tomcat/tmp/dynamicconfig.properties
#      - ./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
#      - ./logging.properties:/usr/local/tomcat/conf/logging.properties
#      - $HOME/eroad/eroad-helpers/application/portal/portal/target/Portal-0-SNAPSHOT:/usr/local/tomcat/webapps/Portal
    ports:
    - 80:8080
    - 9999:8080
    - 8000:8000
    - 9000:9000

  fuel-service-v2:
    image: 212136148154.dkr.ecr.ap-southeast-2.amazonaws.com/fuel-service-v2
    environment:
      AWS_REGION: ap-southeast-2
      AWS_DYNAMODB_TABLE_PROPERTY: ${DEPOT_ENVIRONMENT}ConfigurationDynamoTableProperties
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      JAVA_OPTS: -Dspring.profiles.active=production -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=8686 -Dcom.sun.management.jmxremote.rmi.port=8686 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.local.only=false -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8001
    networks:
      app_net:
        ipv4_address: 172.19.1.19
    volumes:
#      uncomment to deploy locally built application jar
#      - $HOME/eroad/eroad-helpers/application/components/fuel-service-v2/fuel-service-v2-service/target/fuel-service-v2-service-0-SNAPSHOT-exec.jar:/spring-boot/fuelv2.jar
    ports:
    - 8080:8080

  memcached:
    image: 212136148154.dkr.ecr.ap-southeast-2.amazonaws.com/mirrored/docker.io/library/memcached
    networks:
      app_net:
        ipv4_address: 172.19.1.99

  nginx:
    image: 212136148154.dkr.ecr.ap-southeast-2.amazonaws.com/mirrored/docker.io/library/nginx
    networks:
      app_net:
        ipv4_address: 172.19.1.2
    volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.19.1.0/24
