version: "3"
services:
  svc:
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_DYNAMODB_TABLE_PROPERTY: ${DEPOT_ENVIRONMENT}ConfigurationDynamoTableProperties
      AWS_REGION: ap-southeast-2
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      JAVA_OPTS: -DMEMCACHED_NODE_01=memcached:11211 -DMEMCACHED_NODE_02=memcached:11211 -Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=n
    image: 212136148154.dkr.ecr.ap-southeast-2.amazonaws.com/development/svc:latest
    #image : svc-test:latest
    ports: 
      - 80:80
      - 8080:8080
      - 8000:8000
    networks:
      app_net:
        ipv4_address: 172.19.1.20
    volumes:
      - ./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
        #      - ./context.xml:/usr/local/tomcat/conf/context.xml
      - .//dynamicconfig.properties:/usr/local/tomcat/tmp/dynamicconfig.properties
# uncomment to deploy locally built svc component war
      # - ${HOME}/eroad/application/components/ifta/ifta-war/target/ifta-war-5.0.32-SNAPSHOT.war:/usr/local/tomcat/webapps/ifta.war

  memcached:
    image: memcached
    networks:
      app_net:
        ipv4_address: 172.19.1.99

  portal:
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_DYNAMODB_TABLE_PROPERTY: devConfigurationDynamoTableProperties
      AWS_REGION: ap-southeast-2
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      JAVA_OPTS: -DMEMCACHED_NODE_01=memcached:11211 -DMEMCACHED_NODE_02=memcached:11211
    image: 212136148154.dkr.ecr.ap-southeast-2.amazonaws.com/portal
    networks:
      app_net:
        ipv4_address: 172.19.1.95

  nginx:
    image: nginx
    networks:
      app_net:
        aliases:
          - svc.dev.erdmg.com
          - ifta-svc.dev.erdmg.com
          - journey-svc.dev.erdmg.com
          - off-highway-svc.dev.erdmg.com
        ipv4_address: 172.19.1.2
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.1.0/24
      driver: default
