version: '2.0'
services:
  ifta-service-v2:
    depends_on:
    - nginx
    environment:
    - JAVA_OPTS=-Dspring.profiles.active=dev -Xdebug -Xrunjdwp:transport=dt_socket,address=5005,server=y,suspend=n
    - 'CATALINA_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9000 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false'
    - AWS_DYNAMODB_TABLE_PROPERTY=devConfigurationDynamoTableProperties
    - AWS_REGION=ap-southeast-2
    image: 212136148154.dkr.ecr.ap-southeast-2.amazonaws.com/ifta-service-v2
    labels:
      docdepot: 'true'
      docdepot.hostnames: ifta-service-v2.dev.erdmg.com
      docdepot.tomcat: 'true'
    networks:
      docdepot:
        ipv4_address: 172.19.1.111
    volumes:
    - $HOME/.m2/repository/nz/co/eroad/tax/ifta-service-v2-app/0-SNAPSHOT/ifta-service-v2-app-0-SNAPSHOT-exec.jar:/spring-boot/iftav2.jar
    - $HOME/.aws/credentials:/root/.aws/credentials:ro
    - $HOME/.docdepot/tmp:/usr/local/tomcat/tmp/
  memcached:
    image: 212136148154.dkr.ecr.ap-southeast-2.amazonaws.com/mirrored/docker.io/library/memcached
    labels:
      docdepot: 'true'
    networks:
      docdepot:
        ipv4_address: 172.19.1.100
  nginx:
    command: [bash, -c, "echo 'proxy_buffers 4 256k; proxy_buffer_size 128k;server { listen 80; server_name ifta-service-v2.dev.erdmg.com; location / { proxy_pass http://172.19.1.111:8080; } } \nserver { listen 80; server_name depot.local.eroad.io; location / { proxy_pass http://172.19.1.101:8080; } } \n' > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]
    image: 212136148154.dkr.ecr.ap-southeast-2.amazonaws.com/mirrored/docker.io/library/nginx
    labels:
      docdepot: 'true'
    networks:
      docdepot:
        aliases:
        - ifta-service-v2.dev.erdmg.com
        - depot.local.eroad.io
        ipv4_address: 172.19.1.2
  portal:
    depends_on:
    - memcached
    - nginx
    environment:
    - JAVA_OPTS=-DMEMCACHED_NODE_01=memcached:11211 -DMEMCACHED_NODE_02=memcached:11211 -Xdebug -Xrunjdwp:transport=dt_socket,address=5005,server=y,suspend=n
    - 'CATALINA_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9000 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false'
    - AWS_DYNAMODB_TABLE_PROPERTY=devConfigurationDynamoTableProperties
    - AWS_REGION=ap-southeast-2
    image: 212136148154.dkr.ecr.ap-southeast-2.amazonaws.com/portal
    labels:
      docdepot: 'true'
      docdepot.hostnames: depot.local.eroad.io
      docdepot.tomcat: 'true'
    networks:
      docdepot:
        ipv4_address: 172.19.1.101
    volumes:
    - $HOME/.m2/repository/nz/co/eroad/Portal/0-SNAPSHOT/Portal-0-SNAPSHOT.war:/usr/local/tomcat/webapps/Portal.war
    - $HOME/.aws/credentials:/root/.aws/credentials:ro
    - $HOME/.docdepot/tmp:/usr/local/tomcat/tmp/
volumes: {}
networks:
  docdepot:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.19.1.0/24

