version: '3'

services:
  portal:
    image: 212136148154.dkr.ecr.ap-southeast-2.amazonaws.com/portal
    environment:
      AWS_REGION: ${AWS_REGION}
      AWS_DYNAMODB_TABLE_PROPERTY: ${DEPOT_ENVIRONMENT}ConfigurationDynamoTableProperties
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      JAVA_OPTS: -DMEMCACHED_NODE_01=memcached:11211 -DMEMCACHED_NODE_02=memcached:11211 -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000
     # Uncomment to enable JMX connectivity
     # CATALINA_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9000 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false
    networks:
      app_net:
        ipv4_address: 172.19.1.17
    links:
    - memcached:memcached
# uncomment to deploy locally built portal war
    volumes:
      #  - ${LOCAL_CODE_BASE}/portal/target/Portal-0-SNAPSHOT.war:/usr/local/tomcat/webapps/Portal.war
       - ${LOCAL_CODE_BASE}/portal/target/Portal-0-SNAPSHOT:/usr/local/tomcat/webapps/Portal
       - ${LOCAL_CODE_BASE}/portal/src/main/webapp/WEB-INF/jsp:/usr/local/tomcat/webapps/Portal/WEB-INF/jsp
       - ${LOCAL_CODE_BASE}/portal/src/main/webapp/javascript:/usr/local/tomcat/webapps/Portal/javascript
       - ${LOCAL_CODE_BASE}/portal/src/main/webapp/css:/usr/local/tomcat/webapps/Portal/css
       - ./dynamicconfig.properties:/usr/local/tomcat/tmp/dynamicconfig.properties
       - ./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
       - ./logging.properties:/usr/local/tomcat/conf/logging.properties
       - ${LOCAL_CODE_BASE}/portal/build/docker/conf/server.xml:/usr/local/tomcat/conf/server.xml
       - ./eroad-simple-formatter.jar:/usr/local/tomcat/lib/eroad-simple-formatter.jar
       - ${LOCAL_CODE_BASE}/portal/build/docker/bin/setenv.sh:/usr/local/tomcat/bin/setenv.sh

    ports:
    - 80:8080
    - 9999:8080
    - 8000:8000
    - 9000:9000

  # web:
  #   image: "212136148154.dkr.ecr.ap-southeast-2.amazonaws.com/myeroad-portal:PR-5153"
  #   ports:
  #     - 3000:3000    

  memcached:
    image: 212136148154.dkr.ecr.ap-southeast-2.amazonaws.com/mirrored/docker.io/library/memcached
    networks:
      app_net:
        ipv4_address: 172.19.1.99

  nginx:
    image: 212136148154.dkr.ecr.ap-southeast-2.amazonaws.com/mirrored/docker.io/library/nginx
    networks:
      app_net:
        aliases:
        # - depot.local.eroad.io
        - testdepot.eroad.com
        ipv4_address: 172.19.1.2
    volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf
    - ./cert.crt:/etc/nginx/cert.crt
    - ./cert.key:/etc/nginx/cert.key
    depends_on:
      - portal
    # ports:
    # - 443:443

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.19.1.0/24
