version: '3'

services:
  portal:
    image: 212136148154.dkr.ecr.ap-southeast-2.amazonaws.com/portal
    environment:
      AWS_REGION: ap-southeast-2
      AWS_DYNAMODB_TABLE_PROPERTY: ${DEPOT_ENVIRONMENT}ConfigurationDynamoTableProperties
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      JAVA_OPTS: -DMEMCACHED_NODE_01=memcached:11211 -DMEMCACHED_NODE_02=memcached:11211 -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000
    networks:
      app_net:
        ipv4_address: 172.19.1.17
    links:
      - memcached:memcached
# uncomment to deploy locally built portal war
    # volumes:
    #   - ${HOME}/eroad/application/portal/portal/target/Portal-0-SNAPSHOT.war:/usr/local/tomcat/webapps/Portal.war
    #   - .//dynamicconfig.properties:/usr/local/tomcat/tmp/dynamicconfig.properties
    #   - ./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
    ports:
      - 80:8080
      - 9999:8080
    #   - 8000:8000

  memcached:
    image: memcached
    networks:
      app_net:
        ipv4_address: 172.19.1.99

  nginx:
    image: nginx
    networks:
      app_net:
        ipv4_address: 172.19.1.2
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.1.0/24
