version: '3'

services:
  portal:
    image: 212136148154.dkr.ecr.ap-southeast-2.amazonaws.com/portal
    environment:
      AWS_REGION: ap-southeast-2
      AWS_DYNAMODB_TABLE_PROPERTY: devConfigurationDynamoTableProperties
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      JAVA_OPTS: -DMEMCACHED_NODE_01=memcached:11211 -DMEMCACHED_NODE_02=memcached:11211
    networks:
      app_net:
        ipv4_address: 172.19.1.2
    links:
      - memcached:memcached
    volumes:
      - ${HOME}/eroad/application/portal/portal/target/Portal-0-SNAPSHOT.war:/usr/local/tomcat/webapps/Portal.war

  memcached:
    image: memcached
    networks:
      app_net:
        ipv4_address: 172.19.1.99

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.1.0/24
